name: Audit & Install Casks

on:
  push:
    branches:
      - main
    paths:
    - '.github/workflows/*'
    - 'Casks/**'
  workflow_dispatch:

jobs:
  audit:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 1

    - name: Install Homebrew
      if: matrix.os == 'ubuntu-latest'
      uses: Homebrew/actions/setup-homebrew@main

    - name: Update Homebrew
      if: matrix.os != 'ubuntu-latest'
      run: brew update --auto-update

    - name: Enable Rosetta 2
      if: matrix.os != 'ubuntu-latest'
      run: softwareupdate --install-rosetta --agree-to-license

    - name: Install Go
      run: |
        brew uninstall --force go@1.21
        brew cleanup -s go@1.21
        brew cleanup --prune-prefix
        brew install --force go

    - name: Tap Repository
      run: brew tap idleberg/asahi

    - name: Audit Casks
      run: |
        for file in ./Casks/*.rb
        do
          echo "Auditing cask $file"
          brew audit idleberg/asahi/$(basename ${file%.rb}) --cask --online
        done

    - name: Install Casks
      run: |
        for file in ./Casks/*.rb
        do
          echo "Installing cask $file"
          brew install idleberg/asahi/$(basename ${file%.rb}) --cask
        done

    # - name: Test Casks
    #   if: matrix.os == 'ubuntu-latest'
    #   run: |
    #     for file in ./Casks/*.rb
    #     do
    #       echo "Testing cask $file"
    #       brew test $(basename ${file%.rb})
    #     done
